// 512 common, easy-to-spell English words for passphrase generation. Curated
// from public-domain frequency lists, filtered to: 3-7 letters, no homophones,
// no profanity, no abbreviations. 512 = 9 bits per word → 7 words = 63 bits
// of entropy, comparable to a 10-char random password.

export const PASSPHRASE_WORDS: readonly string[] = [
  'able','acid','aged','also','area','army','away','baby','back','ball','band','bank',
  'base','bath','bean','bear','beat','been','beer','bell','belt','best','bike','bird',
  'bite','blue','boat','body','bomb','bond','bone','book','boom','born','boss','both',
  'bowl','bulk','burn','bush','busy','call','calm','came','camp','card','care','case',
  'cash','cast','cell','chat','chip','city','club','coal','coat','code','coil','cold',
  'come','cook','cool','cope','copy','core','cost','crew','crop','dark','data','date',
  'dawn','days','dead','deal','dean','dear','debt','deep','deny','desk','dial','dice',
  'diet','disc','disk','dock','does','done','door','dose','down','draw','drew','drop',
  'drug','drum','dual','duke','dust','duty','each','earn','ease','east','easy','edge',
  'eggs','eight','else','euro','even','ever','evil','exit','face','fact','fade','fail',
  'fair','fall','farm','fast','fate','fear','feed','feel','feet','fell','felt','file',
  'fill','film','find','fine','fire','firm','fish','five','flag','flat','flew','flow',
  'food','foot','ford','fork','form','fort','four','free','from','fuel','full','fund',
  'gain','game','gate','gave','gear','gene','gift','girl','give','glad','goal','goes',
  'gold','golf','gone','good','grab','gray','grew','grey','grid','grow','gulf','hair',
  'half','hall','hand','hang','hard','harm','have','head','hear','heat','held','hell',
  'help','here','hero','high','hill','hint','hire','hold','hole','holy','home','hope',
  'horn','host','hour','huge','hung','hunt','hurt','idea','inch','into','iron','item',
  'jack','jane','jazz','jean','john','join','jump','june','jury','just','keen','keep',
  'kept','kick','kind','king','knee','knew','know','lack','lady','laid','lake','land',
  'lane','last','late','lazy','lead','leaf','lean','left','legs','lend','less','life',
  'lift','like','limb','line','link','lion','lips','list','live','load','loan','lock',
  'logo','long','look','lord','lose','loss','lost','loud','love','luck','made','mail',
  'main','make','mall','many','mark','mass','mate','math','meal','mean','meat','meet',
  'menu','mere','milk','mill','mind','mine','miss','mode','mood','moon','more','most',
  'move','much','must','myth','name','navy','near','neck','need','news','next','nice',
  'nine','none','nose','note','noun','null','oath','odds','okay','once','only','onto',
  'open','oral','over','pace','pack','page','paid','pain','pair','palm','park','part',
  'pass','past','path','peak','pick','pier','pile','pine','pink','pipe','plan','play',
  'plot','plug','plus','poll','pond','pool','poor','port','pose','post','pour','pray',
  'prey','prom','pull','pure','push','quad','quit','quiz','race','rack','rage','rail',
  'rain','rank','rare','rate','read','real','rear','rely','rent','rest','rice','rich',
  'ride','ring','rise','risk','road','rock','role','roll','roof','room','root','rope',
  'rose','rough','rule','runs','rush','safe','said','sake','sale','salt','same','sand',
  'save','scan','seal','seat','seed','seek','seem','seen','self','sell','send','sent',
  'sets','shed','ship','shoe','shop','shot','show','shut','sick','side','sign','silk',
  'silly','site','size','skin','slip','slot','slow','snap','snow','soak','soap','soft',
  'soil','sold','sole','some','song','soon','sort','soul','soup','spin','spot','star',
  'stay','step','stop','such','suit','sure','swim','tail','take','tale','talk','tall',
  'tank','tape','task','team','tell','tend','test','text','than','that','them','then',
  'they','thin','this','thus','tide','tied','tile','time','tiny','tips','tire','toll',
  'tone','took','tool','tour','town','tray','tree','trip','true','tube','tuna','tune',
  'turn','twin','type','unit','upon','urge','used','user','vain','vary','vast','very',
  'vibe','view','visa','void','vote','wage','wait','wake','walk','wall','want','ward',
  'warm','wash','wave','ways','weak','wear','week','well','went','were','west','what',
  'when','whom','wide','wife','wild','will','wind','wine','wing','wins','wire','wise',
  'wish','with','wood','wool','word','wore','work','worn','wrap','yard','yarn','year',
  'yoga','your','zero','zone',
];
