export interface Tool {
  id: string;
  name: string;
  description: string;
  shortDescription: string;
  category: string;
  slug: string;
  icon: string;
  keywords: string[];
  faq?: {
    question: string;
    answer: string;
  }[];
  relatedTools?: string[];
  howToUse?: string[];
}

export const tools: Tool[] = [
  // ==================== DEVELOPER TOOLS ====================
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format and beautify your JSON data with syntax highlighting. This online JSON formatter makes your JSON data easy to read and debug.',
    shortDescription: 'Format and beautify JSON data online',
    category: 'dev',
    slug: 'json-formatter',
    icon: 'Braces',
    keywords: ['json', 'formatter', 'beautify', 'format json', 'json parser', 'json validator'],
    faq: [
      {
        question: 'What is JSON Formatter?',
        answer: 'JSON Formatter is an online tool that helps you format and beautify JSON data. It takes compressed or minified JSON and adds proper indentation and line breaks to make it human-readable.',
      },
      {
        question: 'Is my JSON data secure?',
        answer: 'Yes, all processing happens in your browser. Your JSON data is never sent to any server, ensuring complete privacy and security.',
      },
    ],
    relatedTools: ['json-validator', 'json-to-yaml', 'base64-encode'],
    howToUse: [
      'Paste your JSON data into the input field above',
      'Click the "Format" button to beautify your JSON or "Minify" to compress it',
      'The result will appear in the output area',
      'Use the copy button to copy the result to your clipboard',
    ],
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    description: 'Validate your JSON data and find errors quickly. Get detailed error messages to help fix invalid JSON.',
    shortDescription: 'Validate JSON and find errors',
    category: 'dev',
    slug: 'json-validator',
    icon: 'CheckCircle',
    keywords: ['json', 'validator', 'validate json', 'json checker', 'json lint'],
    relatedTools: ['json-formatter', 'json-to-yaml'],
    howToUse: [
      'Paste your JSON data into the input field',
      'Click "Validate" to check if your JSON is valid',
      'View validation results and error details if any',
    ],
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML Converter',
    description: 'Convert JSON data to YAML format instantly. Easy to use with copy to clipboard functionality.',
    shortDescription: 'Convert JSON to YAML format',
    category: 'dev',
    slug: 'json-to-yaml',
    icon: 'FileCode',
    keywords: ['json', 'yaml', 'converter', 'json to yaml', 'convert json'],
    relatedTools: ['json-formatter', 'yaml-to-json'],
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON Converter',
    description: 'Convert YAML data to JSON format instantly. Easy to use with proper formatting and validation.',
    shortDescription: 'Convert YAML to JSON format',
    category: 'dev',
    slug: 'yaml-to-json',
    icon: 'FileCode',
    keywords: ['yaml', 'json', 'converter', 'yaml to json', 'convert yaml'],
    relatedTools: ['json-to-yaml', 'json-formatter'],
  },
  {
    id: 'base64-encode',
    name: 'Base64 Encoder',
    description: 'Encode text or data to Base64 format instantly. Simple and fast online Base64 encoding tool.',
    shortDescription: 'Encode text to Base64 format',
    category: 'dev',
    slug: 'base64-encode',
    icon: 'Lock',
    keywords: ['base64', 'encode', 'encoder', 'base64 encode', 'text encoder'],
    faq: [
      {
        question: 'What is Base64 encoding?',
        answer: 'Base64 is a binary-to-text encoding scheme that converts binary data into an ASCII string format. It is commonly used to encode data for safe transmission over media designed to handle text.',
      },
    ],
    relatedTools: ['base64-decode', 'url-encode'],
  },
  {
    id: 'base64-decode',
    name: 'Base64 Decoder',
    description: 'Decode Base64 encoded text back to its original format. Fast and easy online Base64 decoding.',
    shortDescription: 'Decode Base64 to text',
    category: 'dev',
    slug: 'base64-decode',
    icon: 'Unlock',
    keywords: ['base64', 'decode', 'decoder', 'base64 decode', 'text decoder'],
    relatedTools: ['base64-encode', 'url-decode'],
  },
  {
    id: 'url-encode',
    name: 'URL Encoder',
    description: 'Encode URLs and text for safe transmission. Convert special characters to URL-safe format.',
    shortDescription: 'Encode URLs and text',
    category: 'dev',
    slug: 'url-encode',
    icon: 'Link',
    keywords: ['url', 'encode', 'encoder', 'url encode', 'percent encoding'],
    relatedTools: ['url-decode', 'base64-encode'],
  },
  {
    id: 'url-decode',
    name: 'URL Decoder',
    description: 'Decode URL-encoded text back to its original format. Handle percent-encoded strings easily.',
    shortDescription: 'Decode URL-encoded text',
    category: 'dev',
    slug: 'url-decode',
    icon: 'Unlink',
    keywords: ['url', 'decode', 'decoder', 'url decode', 'percent decoding'],
    relatedTools: ['url-encode', 'base64-decode'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate unique UUIDs (Universally Unique Identifiers) instantly. Create multiple UUIDs v4 for your projects.',
    shortDescription: 'Generate unique UUIDs online',
    category: 'dev',
    slug: 'uuid-generator',
    icon: 'Fingerprint',
    keywords: ['uuid', 'guid', 'generator', 'unique id', 'uuid v4'],
    faq: [
      {
        question: 'What is a UUID?',
        answer: 'UUID (Universally Unique Identifier) is a 128-bit number used to identify information in computer systems. UUID v4 is randomly generated and has an extremely low probability of duplication.',
      },
    ],
    relatedTools: ['random-password-generator', 'random-number-generator'],
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and vice versa. Support for multiple date formats.',
    shortDescription: 'Convert Unix timestamps to dates',
    category: 'dev',
    slug: 'timestamp-converter',
    icon: 'Clock',
    keywords: ['timestamp', 'unix', 'converter', 'epoch', 'date converter'],
    relatedTools: ['uuid-generator', 'date-to-unix-time'],
  },
  {
    id: 'random-password-generator',
    name: 'Random Password Generator',
    description: 'Generate secure random passwords with customizable options. Include uppercase, lowercase, numbers, and symbols.',
    shortDescription: 'Generate secure random passwords',
    category: 'dev',
    slug: 'random-password-generator',
    icon: 'Key',
    keywords: ['password', 'generator', 'random', 'secure password', 'password maker'],
    relatedTools: ['uuid-generator', 'password-strength-checker'],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions with real-time matching. Highlight matches and capture groups.',
    shortDescription: 'Test regular expressions online',
    category: 'dev',
    slug: 'regex-tester',
    icon: 'Regex',
    keywords: ['regex', 'regexp', 'regular expression', 'tester', 'pattern matcher'],
    relatedTools: ['text-case-converter', 'find-and-replace'],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (JWT). View header, payload, and signature details.',
    shortDescription: 'Decode JWT tokens online',
    category: 'dev',
    slug: 'jwt-decoder',
    icon: 'Shield',
    keywords: ['jwt', 'json web token', 'decoder', 'token', 'authentication'],
    relatedTools: ['base64-decode', 'json-formatter'],
  },
  {
    id: 'md5-hash-generator',
    name: 'MD5 Hash Generator',
    description: 'Generate MD5 hash from text or strings. Fast and easy online MD5 checksum generator.',
    shortDescription: 'Generate MD5 hash online',
    category: 'dev',
    slug: 'md5-hash-generator',
    icon: 'Hash',
    keywords: ['md5', 'hash', 'generator', 'checksum', 'md5 hash'],
    relatedTools: ['sha256-hash-generator', 'base64-encode'],
  },
  {
    id: 'sha256-hash-generator',
    name: 'SHA256 Hash Generator',
    description: 'Generate SHA256 hash from text or strings. Secure cryptographic hash function for data integrity.',
    shortDescription: 'Generate SHA256 hash online',
    category: 'dev',
    slug: 'sha256-hash-generator',
    icon: 'Hash',
    keywords: ['sha256', 'hash', 'generator', 'checksum', 'secure hash'],
    relatedTools: ['md5-hash-generator', 'base64-encode'],
  },
  {
    id: 'html-formatter',
    name: 'HTML Formatter',
    description: 'Format and beautify HTML code with proper indentation. Make your HTML code clean and readable.',
    shortDescription: 'Format and beautify HTML code',
    category: 'dev',
    slug: 'html-formatter',
    icon: 'Code',
    keywords: ['html', 'formatter', 'beautify', 'format html', 'html prettifier'],
    relatedTools: ['css-formatter', 'json-formatter'],
  },
  {
    id: 'css-formatter',
    name: 'CSS Formatter',
    description: 'Format and beautify CSS code with proper indentation. Make your CSS stylesheets clean and organized.',
    shortDescription: 'Format and beautify CSS code',
    category: 'dev',
    slug: 'css-formatter',
    icon: 'Palette',
    keywords: ['css', 'formatter', 'beautify', 'format css', 'css prettifier'],
    relatedTools: ['html-formatter', 'json-formatter'],
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries with proper indentation. Make your SQL code clean and readable.',
    shortDescription: 'Format and beautify SQL queries',
    category: 'dev',
    slug: 'sql-formatter',
    icon: 'Database',
    keywords: ['sql', 'formatter', 'beautify', 'format sql', 'sql prettifier'],
    relatedTools: ['json-formatter', 'html-formatter'],
  },
  {
    id: 'ip-address-validator',
    name: 'IP Address Validator',
    description: 'Validate IPv4 and IPv6 addresses. Check if an IP address is valid and get detailed information.',
    shortDescription: 'Validate IP addresses online',
    category: 'dev',
    slug: 'ip-address-validator',
    icon: 'Globe',
    keywords: ['ip', 'ip address', 'validator', 'ipv4', 'ipv6'],
    relatedTools: ['url-encode', 'base64-encode'],
  },
  {
    id: 'cron-expression-parser',
    name: 'Cron Expression Parser',
    description: 'Parse and explain cron expressions. Understand when your cron jobs will run with human-readable output.',
    shortDescription: 'Parse cron expressions online',
    category: 'dev',
    slug: 'cron-expression-parser',
    icon: 'Timer',
    keywords: ['cron', 'expression', 'parser', 'schedule', 'cron job'],
    relatedTools: ['timestamp-converter', 'uuid-generator'],
  },

  // ==================== TEXT TOOLS ====================
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and paragraphs in your text. Perfect for writers and students.',
    shortDescription: 'Count words and characters',
    category: 'text',
    slug: 'word-counter',
    icon: 'Hash',
    keywords: ['word counter', 'character count', 'word count', 'text counter'],
    relatedTools: ['character-counter', 'text-case-converter'],
  },
  {
    id: 'character-counter',
    name: 'Character Counter',
    description: 'Count characters, letters, numbers, and symbols in your text. Get detailed text statistics.',
    shortDescription: 'Count characters in text',
    category: 'text',
    slug: 'character-counter',
    icon: 'Type',
    keywords: ['character counter', 'char count', 'letter count', 'text statistics'],
    relatedTools: ['word-counter', 'text-case-converter'],
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Convert text to uppercase, lowercase, title case, sentence case, and more. Transform your text instantly.',
    shortDescription: 'Convert text case online',
    category: 'text',
    slug: 'text-case-converter',
    icon: 'CaseSensitive',
    keywords: ['case converter', 'uppercase', 'lowercase', 'title case', 'text transform'],
    relatedTools: ['word-counter', 'slug-generator'],
  },
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'Generate URL-friendly slugs from text. Create SEO-friendly URLs for your blog posts and pages.',
    shortDescription: 'Generate URL slugs online',
    category: 'text',
    slug: 'slug-generator',
    icon: 'Link',
    keywords: ['slug generator', 'url slug', 'seo slug', 'permalink', 'url friendly'],
    relatedTools: ['text-case-converter', 'url-encode'],
  },
  {
    id: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    description: 'Remove duplicate lines from text instantly. Keep only unique lines in your text.',
    shortDescription: 'Remove duplicate lines from text',
    category: 'text',
    slug: 'remove-duplicate-lines',
    icon: 'ListX',
    keywords: ['remove duplicates', 'unique lines', 'dedupe', 'duplicate remover'],
    relatedTools: ['sort-lines-alphabetically', 'text-cleaner'],
  },
  {
    id: 'sort-lines-alphabetically',
    name: 'Sort Lines Alphabetically',
    description: 'Sort lines of text alphabetically (A-Z or Z-A). Organize your lists quickly and easily.',
    shortDescription: 'Sort text lines alphabetically',
    category: 'text',
    slug: 'sort-lines-alphabetically',
    icon: 'ListOrdered',
    keywords: ['sort lines', 'alphabetical sort', 'sort text', 'order lines'],
    relatedTools: ['remove-duplicate-lines', 'reverse-text'],
  },
  {
    id: 'reverse-text',
    name: 'Reverse Text',
    description: 'Reverse text characters or words. Flip your text backwards for creative purposes.',
    shortDescription: 'Reverse text online',
    category: 'text',
    slug: 'reverse-text',
    icon: 'Reverse',
    keywords: ['reverse text', 'flip text', 'backwards text', 'text reverser'],
    relatedTools: ['sort-lines-alphabetically', 'text-case-converter'],
  },
  {
    id: 'remove-line-breaks',
    name: 'Remove Line Breaks',
    description: 'Remove line breaks and convert text to a single line. Join paragraphs into one continuous line.',
    shortDescription: 'Remove line breaks from text',
    category: 'text',
    slug: 'remove-line-breaks',
    icon: 'Minus',
    keywords: ['remove line breaks', 'join lines', 'single line', 'remove newlines'],
    relatedTools: ['remove-extra-spaces', 'text-cleaner'],
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for your designs and layouts. Choose paragraphs, words, or sentences.',
    shortDescription: 'Generate placeholder text',
    category: 'text',
    slug: 'lorem-ipsum',
    icon: 'AlignLeft',
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text', 'lipsum'],
    relatedTools: ['word-counter', 'random-text-generator'],
  },
  {
    id: 'random-text-generator',
    name: 'Random Text Generator',
    description: 'Generate random text for testing and mockups. Create realistic-looking content for your projects.',
    shortDescription: 'Generate random text online',
    category: 'text',
    slug: 'random-text-generator',
    icon: 'Text',
    keywords: ['random text', 'text generator', 'dummy content', 'test text'],
    relatedTools: ['lorem-ipsum', 'random-name-generator'],
  },
  {
    id: 'text-difference-checker',
    name: 'Text Difference Checker',
    description: 'Compare two texts and find differences. Highlight added, removed, and changed text.',
    shortDescription: 'Compare texts and find differences',
    category: 'text',
    slug: 'text-difference-checker',
    icon: 'Diff',
    keywords: ['text diff', 'compare text', 'difference checker', 'text compare'],
    relatedTools: ['find-and-replace', 'word-counter'],
  },
  {
    id: 'remove-html-tags',
    name: 'Remove HTML Tags',
    description: 'Strip HTML tags from text and get clean plain text. Remove all markup from your content.',
    shortDescription: 'Remove HTML tags from text',
    category: 'text',
    slug: 'remove-html-tags',
    icon: 'CodeX',
    keywords: ['remove html', 'strip tags', 'html remover', 'plain text'],
    relatedTools: ['html-formatter', 'markdown-to-html'],
  },
  {
    id: 'find-and-replace',
    name: 'Find and Replace',
    description: 'Find and replace text in your content. Support for case-sensitive and whole word matching.',
    shortDescription: 'Find and replace text online',
    category: 'text',
    slug: 'find-and-replace',
    icon: 'Replace',
    keywords: ['find replace', 'search replace', 'text replace', 'replace all'],
    relatedTools: ['regex-tester', 'text-difference-checker'],
  },
  {
    id: 'text-to-list',
    name: 'Text to List Converter',
    description: 'Convert text to a list format. Transform paragraphs into bullet points or numbered lists.',
    shortDescription: 'Convert text to list format',
    category: 'text',
    slug: 'text-to-list',
    icon: 'List',
    keywords: ['text to list', 'convert to list', 'list maker', 'bullet points'],
    relatedTools: ['list-to-text', 'remove-duplicate-lines'],
  },
  {
    id: 'list-to-text',
    name: 'List to Text Converter',
    description: 'Convert lists to plain text format. Join list items into a single paragraph.',
    shortDescription: 'Convert list to text format',
    category: 'text',
    slug: 'list-to-text',
    icon: 'FileText',
    keywords: ['list to text', 'convert list', 'join list', 'list to paragraph'],
    relatedTools: ['text-to-list', 'remove-line-breaks'],
  },
  {
    id: 'random-name-generator',
    name: 'Random Name Generator',
    description: 'Generate random names for characters, testing, or inspiration. Choose gender and quantity.',
    shortDescription: 'Generate random names online',
    category: 'text',
    slug: 'random-name-generator',
    icon: 'User',
    keywords: ['name generator', 'random names', 'fake names', 'name picker'],
    relatedTools: ['random-text-generator', 'random-number-generator'],
  },
  {
    id: 'remove-extra-spaces',
    name: 'Remove Extra Spaces',
    description: 'Remove extra spaces, tabs, and whitespace from text. Clean up messy formatting.',
    shortDescription: 'Remove extra spaces from text',
    category: 'text',
    slug: 'remove-extra-spaces',
    icon: 'Space',
    keywords: ['remove spaces', 'extra spaces', 'whitespace remover', 'clean spaces'],
    relatedTools: ['remove-line-breaks', 'text-cleaner'],
  },
  {
    id: 'capitalize-sentences',
    name: 'Capitalize Sentences',
    description: 'Capitalize the first letter of each sentence. Fix capitalization in your text automatically.',
    shortDescription: 'Capitalize sentences online',
    category: 'text',
    slug: 'capitalize-sentences',
    icon: 'CaseUpper',
    keywords: ['capitalize sentences', 'sentence case', 'fix capitalization', 'capitalize first letter'],
    relatedTools: ['text-case-converter', 'text-cleaner'],
  },
  {
    id: 'text-cleaner',
    name: 'Text Cleaner',
    description: 'Clean and format text by removing extra spaces, line breaks, and unwanted characters.',
    shortDescription: 'Clean and format text online',
    category: 'text',
    slug: 'text-cleaner',
    icon: 'Eraser',
    keywords: ['text cleaner', 'clean text', 'format text', 'text sanitizer'],
    relatedTools: ['remove-extra-spaces', 'remove-line-breaks'],
  },
  {
    id: 'text-formatter',
    name: 'Text Formatter',
    description: 'Format text with various options. Add line breaks, paragraphs, and apply text transformations.',
    shortDescription: 'Format text online',
    category: 'text',
    slug: 'text-formatter',
    icon: 'TextCursor',
    keywords: ['text formatter', 'format text', 'text styling', 'text layout'],
    relatedTools: ['text-case-converter', 'text-cleaner'],
  },

  // ==================== IMAGE TOOLS ====================
  {
    id: 'image-resize',
    name: 'Image Resizer',
    description: 'Resize images online without losing quality. Support for PNG, JPG, and WebP formats.',
    shortDescription: 'Resize images online',
    category: 'image',
    slug: 'image-resize',
    icon: 'Scaling',
    keywords: ['image resize', 'resize photo', 'picture resizer', 'image size'],
    relatedTools: ['resize-image-percentage', 'resize-image-dimensions'],
  },
  {
    id: 'image-to-base64',
    name: 'Image to Base64',
    description: 'Convert images to Base64 encoded strings. Perfect for embedding images in HTML, CSS, or JSON.',
    shortDescription: 'Convert image to Base64',
    category: 'image',
    slug: 'image-to-base64',
    icon: 'Binary',
    keywords: ['image to base64', 'base64 image', 'encode image', 'image encoder'],
    relatedTools: ['base64-to-image', 'image-to-ico'],
  },
  {
    id: 'base64-to-image',
    name: 'Base64 to Image',
    description: 'Convert Base64 encoded strings back to images. Download the decoded image file.',
    shortDescription: 'Convert Base64 to image',
    category: 'image',
    slug: 'base64-to-image',
    icon: 'Image',
    keywords: ['base64 to image', 'decode image', 'base64 decoder', 'image decoder'],
    relatedTools: ['image-to-base64', 'base64-decode'],
  },
  {
    id: 'image-to-ico',
    name: 'Image to ICO Converter',
    description: 'Convert PNG or JPG images to ICO format for favicons. Create multi-resolution icon files.',
    shortDescription: 'Convert image to ICO format',
    category: 'image',
    slug: 'image-to-ico',
    icon: 'FileImage',
    keywords: ['image to ico', 'ico converter', 'favicon generator', 'icon maker'],
    relatedTools: ['favicon-generator', 'image-to-base64'],
  },
  {
    id: 'webp-to-png',
    name: 'WebP to PNG Converter',
    description: 'Convert WebP images to PNG format online. Fast and free WebP to PNG conversion.',
    shortDescription: 'Convert WebP to PNG',
    category: 'image',
    slug: 'webp-to-png',
    icon: 'ImageDown',
    keywords: ['webp to png', 'convert webp', 'webp converter', 'image converter'],
    relatedTools: ['png-to-webp', 'jpg-to-png'],
  },
  {
    id: 'png-to-webp',
    name: 'PNG to WebP Converter',
    description: 'Convert PNG images to WebP format for smaller file sizes. Optimize your images for the web.',
    shortDescription: 'Convert PNG to WebP',
    category: 'image',
    slug: 'png-to-webp',
    icon: 'ImageUp',
    keywords: ['png to webp', 'convert png', 'webp converter', 'image optimization'],
    relatedTools: ['webp-to-png', 'png-to-jpg'],
  },
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG Converter',
    description: 'Convert JPG/JPEG images to PNG format with transparency support. Free online conversion.',
    shortDescription: 'Convert JPG to PNG',
    category: 'image',
    slug: 'jpg-to-png',
    icon: 'ImageOff',
    keywords: ['jpg to png', 'jpeg to png', 'convert jpg', 'image converter'],
    relatedTools: ['png-to-jpg', 'webp-to-png'],
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG Converter',
    description: 'Convert PNG images to JPG format for smaller file sizes. Fast and easy online conversion.',
    shortDescription: 'Convert PNG to JPG',
    category: 'image',
    slug: 'png-to-jpg',
    icon: 'ImagePlus',
    keywords: ['png to jpg', 'convert png', 'jpg converter', 'image converter'],
    relatedTools: ['jpg-to-png', 'png-to-webp'],
  },
  {
    id: 'resize-image-percentage',
    name: 'Resize Image by Percentage',
    description: 'Resize images by percentage. Scale your photos up or down while maintaining aspect ratio.',
    shortDescription: 'Resize image by percentage',
    category: 'image',
    slug: 'resize-image-percentage',
    icon: 'Percent',
    keywords: ['resize percentage', 'scale image', 'image percentage', 'resize by percent'],
    relatedTools: ['image-resize', 'resize-image-dimensions'],
  },
  {
    id: 'resize-image-dimensions',
    name: 'Resize Image by Dimensions',
    description: 'Resize images to specific width and height. Set exact pixel dimensions for your images.',
    shortDescription: 'Resize image to specific dimensions',
    category: 'image',
    slug: 'resize-image-dimensions',
    icon: 'Maximize',
    keywords: ['resize dimensions', 'exact size', 'image dimensions', 'pixel size'],
    relatedTools: ['image-resize', 'resize-image-percentage'],
  },
  {
    id: 'rotate-image',
    name: 'Rotate Image',
    description: 'Rotate images by any angle. Flip and rotate photos 90, 180, or 270 degrees.',
    shortDescription: 'Rotate images online',
    category: 'image',
    slug: 'rotate-image',
    icon: 'RotateCw',
    keywords: ['rotate image', 'rotate photo', 'image rotation', 'flip image'],
    relatedTools: ['flip-image-horizontal', 'flip-image-vertical'],
  },
  {
    id: 'flip-image-horizontal',
    name: 'Flip Image Horizontal',
    description: 'Flip images horizontally (mirror). Create a mirror image of your photos.',
    shortDescription: 'Flip image horizontally',
    category: 'image',
    slug: 'flip-image-horizontal',
    icon: 'FlipHorizontal',
    keywords: ['flip horizontal', 'mirror image', 'horizontal flip', 'flip photo'],
    relatedTools: ['flip-image-vertical', 'rotate-image'],
  },
  {
    id: 'flip-image-vertical',
    name: 'Flip Image Vertical',
    description: 'Flip images vertically. Create an upside-down mirror of your photos.',
    shortDescription: 'Flip image vertically',
    category: 'image',
    slug: 'flip-image-vertical',
    icon: 'FlipVertical',
    keywords: ['flip vertical', 'vertical flip', 'flip photo', 'mirror vertical'],
    relatedTools: ['flip-image-horizontal', 'rotate-image'],
  },
  {
    id: 'blur-image',
    name: 'Blur Image',
    description: 'Blur images online with adjustable blur intensity. Privacy protection and creative effects.',
    shortDescription: 'Blur images online',
    category: 'image',
    slug: 'blur-image',
    icon: 'EyeOff',
    keywords: ['blur image', 'image blur', 'blur photo', 'blur effect'],
    relatedTools: ['pixelate-image', 'grayscale-image'],
  },
  {
    id: 'pixelate-image',
    name: 'Pixelate Image',
    description: 'Pixelate images for privacy or artistic effects. Adjust pixel size for desired effect.',
    shortDescription: 'Pixelate images online',
    category: 'image',
    slug: 'pixelate-image',
    icon: 'Grid3x3',
    keywords: ['pixelate image', 'pixel effect', 'mosaic effect', 'pixelate photo'],
    relatedTools: ['blur-image', 'grayscale-image'],
  },
  {
    id: 'grayscale-image',
    name: 'Grayscale Image',
    description: 'Convert images to grayscale (black and white). Create classic black and white photos.',
    shortDescription: 'Convert image to grayscale',
    category: 'image',
    slug: 'grayscale-image',
    icon: 'CircleHalf',
    keywords: ['grayscale', 'black and white', 'bw image', 'monochrome'],
    relatedTools: ['blur-image', 'adjust-brightness'],
  },
  {
    id: 'adjust-brightness',
    name: 'Adjust Image Brightness',
    description: 'Adjust brightness and contrast of images. Make your photos lighter or darker.',
    shortDescription: 'Adjust image brightness',
    category: 'image',
    slug: 'adjust-brightness',
    icon: 'Sun',
    keywords: ['brightness', 'adjust brightness', 'image brightness', 'photo brightness'],
    relatedTools: ['grayscale-image', 'blur-image'],
  },
  {
    id: 'image-color-picker',
    name: 'Image Color Picker',
    description: 'Pick colors from images and get HEX, RGB, and HSL values. Extract colors from any image.',
    shortDescription: 'Pick colors from images',
    category: 'image',
    slug: 'image-color-picker',
    icon: 'Pipette',
    keywords: ['color picker', 'image color', 'pick color', 'extract color'],
    relatedTools: ['color-picker', 'extract-colors'],
  },
  {
    id: 'extract-colors',
    name: 'Extract Colors from Image',
    description: 'Extract dominant colors from images. Get color palettes from any photo.',
    shortDescription: 'Extract colors from images',
    category: 'image',
    slug: 'extract-colors',
    icon: 'Palette',
    keywords: ['extract colors', 'color palette', 'dominant colors', 'image colors'],
    relatedTools: ['image-color-picker', 'color-palette-generator'],
  },
  {
    id: 'image-border',
    name: 'Add Image Border',
    description: 'Add custom borders to images. Choose border color, width, and style.',
    shortDescription: 'Add border to image',
    category: 'image',
    slug: 'image-border',
    icon: 'Frame',
    keywords: ['image border', 'add border', 'photo border', 'picture frame'],
    relatedTools: ['rotate-image', 'resize-image-dimensions'],
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Generate favicons for your website from any image. Create multi-size favicon files.',
    shortDescription: 'Generate favicon online',
    category: 'image',
    slug: 'favicon-generator',
    icon: 'Star',
    keywords: ['favicon', 'favicon generator', 'website icon', 'browser icon'],
    relatedTools: ['image-to-ico', 'image-resize'],
  },

  // ==================== YOUTUBE TOOLS ====================
  {
    id: 'youtube-thumbnail',
    name: 'YouTube Thumbnail Downloader',
    description: 'Download YouTube video thumbnails in HD, SD, and Max resolution. Just paste the video URL.',
    shortDescription: 'Download YouTube thumbnails',
    category: 'youtube',
    slug: 'youtube-thumbnail',
    icon: 'Image',
    keywords: ['youtube', 'thumbnail', 'downloader', 'youtube thumbnail', 'video thumbnail'],
    relatedTools: ['youtube-video-id-extractor', 'youtube-embed-generator'],
  },
  {
    id: 'youtube-tag-extractor',
    name: 'YouTube Tag Extractor',
    description: 'Extract tags from YouTube videos. Discover what tags competitors are using.',
    shortDescription: 'Extract YouTube video tags',
    category: 'youtube',
    slug: 'youtube-tag-extractor',
    icon: 'Tags',
    keywords: ['youtube tags', 'tag extractor', 'video tags', 'youtube seo'],
    relatedTools: ['youtube-hashtag-generator', 'youtube-title-generator'],
  },
  {
    id: 'youtube-title-generator',
    name: 'YouTube Title Generator',
    description: 'Generate SEO-optimized titles for your YouTube videos. Get more views with better titles.',
    shortDescription: 'Generate YouTube titles',
    category: 'youtube',
    slug: 'youtube-title-generator',
    icon: 'Heading',
    keywords: ['youtube title', 'title generator', 'video title', 'youtube seo'],
    relatedTools: ['youtube-description-generator', 'youtube-tag-extractor'],
  },
  {
    id: 'youtube-description-generator',
    name: 'YouTube Description Generator',
    description: 'Generate optimized descriptions for YouTube videos. Include keywords and calls to action.',
    shortDescription: 'Generate YouTube descriptions',
    category: 'youtube',
    slug: 'youtube-description-generator',
    icon: 'FileText',
    keywords: ['youtube description', 'description generator', 'video description'],
    relatedTools: ['youtube-title-generator', 'youtube-hashtag-generator'],
  },
  {
    id: 'youtube-hashtag-generator',
    name: 'YouTube Hashtag Generator',
    description: 'Generate relevant hashtags for YouTube videos. Improve discoverability of your content.',
    shortDescription: 'Generate YouTube hashtags',
    category: 'youtube',
    slug: 'youtube-hashtag-generator',
    icon: 'Hash',
    keywords: ['youtube hashtag', 'hashtag generator', 'video hashtags', 'youtube seo'],
    relatedTools: ['youtube-tag-extractor', 'youtube-description-generator'],
  },
  {
    id: 'youtube-timestamp-generator',
    name: 'YouTube Timestamp Generator',
    description: 'Generate timestamp links for YouTube videos. Create clickable time codes for your videos.',
    shortDescription: 'Generate YouTube timestamps',
    category: 'youtube',
    slug: 'youtube-timestamp-generator',
    icon: 'Clock',
    keywords: ['youtube timestamp', 'timestamp generator', 'video timestamp', 'time codes'],
    relatedTools: ['youtube-embed-generator', 'youtube-video-id-extractor'],
  },
  {
    id: 'youtube-embed-generator',
    name: 'YouTube Embed Generator',
    description: 'Generate embed codes for YouTube videos. Customize player options and get HTML code.',
    shortDescription: 'Generate YouTube embed code',
    category: 'youtube',
    slug: 'youtube-embed-generator',
    icon: 'Code',
    keywords: ['youtube embed', 'embed generator', 'video embed', 'iframe code'],
    relatedTools: ['youtube-thumbnail', 'youtube-video-id-extractor'],
  },
  {
    id: 'youtube-channel-id-finder',
    name: 'YouTube Channel ID Finder',
    description: 'Find the Channel ID of any YouTube channel. Get unique identifiers for channels.',
    shortDescription: 'Find YouTube channel IDs',
    category: 'youtube',
    slug: 'youtube-channel-id-finder',
    icon: 'User',
    keywords: ['youtube channel id', 'channel id finder', 'youtube channel'],
    relatedTools: ['youtube-video-id-extractor', 'youtube-playlist-id-extractor'],
  },
  {
    id: 'youtube-video-id-extractor',
    name: 'YouTube Video ID Extractor',
    description: 'Extract the video ID from any YouTube URL. Get the unique identifier for videos.',
    shortDescription: 'Extract YouTube video IDs',
    category: 'youtube',
    slug: 'youtube-video-id-extractor',
    icon: 'Video',
    keywords: ['youtube video id', 'video id extractor', 'youtube id'],
    relatedTools: ['youtube-thumbnail', 'youtube-embed-generator'],
  },
  {
    id: 'youtube-playlist-id-extractor',
    name: 'YouTube Playlist ID Extractor',
    description: 'Extract the playlist ID from YouTube playlist URLs. Get unique identifiers for playlists.',
    shortDescription: 'Extract YouTube playlist IDs',
    category: 'youtube',
    slug: 'youtube-playlist-id-extractor',
    icon: 'ListVideo',
    keywords: ['youtube playlist id', 'playlist id extractor', 'youtube playlist'],
    relatedTools: ['youtube-video-id-extractor', 'youtube-channel-id-finder'],
  },

  // ==================== COLOR TOOLS ====================
  {
    id: 'color-picker',
    name: 'Color Picker',
    description: 'Pick colors and get HEX, RGB, HSL values. Easy to use color picker with multiple format outputs.',
    shortDescription: 'Pick colors and get color codes',
    category: 'color',
    slug: 'color-picker',
    icon: 'Pipette',
    keywords: ['color picker', 'hex color', 'rgb color', 'color code'],
    relatedTools: ['hex-to-rgb', 'color-converter'],
  },
  {
    id: 'hex-to-rgb',
    name: 'HEX to RGB Converter',
    description: 'Convert HEX color codes to RGB values. Get red, green, and blue color components.',
    shortDescription: 'Convert HEX to RGB',
    category: 'color',
    slug: 'hex-to-rgb',
    icon: 'Palette',
    keywords: ['hex to rgb', 'color converter', 'hex color', 'rgb color'],
    relatedTools: ['rgb-to-hex', 'color-picker'],
  },
  {
    id: 'rgb-to-hex',
    name: 'RGB to HEX Converter',
    description: 'Convert RGB color values to HEX codes. Transform red, green, blue to hexadecimal.',
    shortDescription: 'Convert RGB to HEX',
    category: 'color',
    slug: 'rgb-to-hex',
    icon: 'Palette',
    keywords: ['rgb to hex', 'color converter', 'rgb color', 'hex color'],
    relatedTools: ['hex-to-rgb', 'color-picker'],
  },
  {
    id: 'color-palette-generator',
    name: 'Color Palette Generator',
    description: 'Generate beautiful color palettes for your designs. Create harmonious color schemes.',
    shortDescription: 'Generate color palettes',
    category: 'color',
    slug: 'color-palette-generator',
    icon: 'SwatchBook',
    keywords: ['color palette', 'palette generator', 'color scheme', 'color combination'],
    relatedTools: ['color-picker', 'gradient-generator'],
  },
  {
    id: 'gradient-generator',
    name: 'CSS Gradient Generator',
    description: 'Create beautiful CSS gradients for your designs. Generate linear and radial gradients.',
    shortDescription: 'Generate CSS gradients',
    category: 'color',
    slug: 'gradient-generator',
    icon: 'Blend',
    keywords: ['gradient generator', 'css gradient', 'linear gradient', 'radial gradient'],
    relatedTools: ['css-gradient-generator', 'color-palette-generator'],
  },
  {
    id: 'color-contrast-checker',
    name: 'Color Contrast Checker',
    description: 'Check color contrast for accessibility. Ensure your colors meet WCAG guidelines.',
    shortDescription: 'Check color contrast',
    category: 'color',
    slug: 'color-contrast-checker',
    icon: 'Contrast',
    keywords: ['contrast checker', 'wcag', 'accessibility', 'color contrast'],
    relatedTools: ['color-picker', 'hex-to-rgb'],
  },
  {
    id: 'css-gradient-generator',
    name: 'CSS Gradient Generator',
    description: 'Generate CSS gradient code with preview. Create and copy gradient CSS easily.',
    shortDescription: 'Generate CSS gradient code',
    category: 'color',
    slug: 'css-gradient-generator',
    icon: 'Blend',
    keywords: ['css gradient', 'gradient css', 'gradient code', 'css generator'],
    relatedTools: ['gradient-generator', 'color-palette-generator'],
  },
  {
    id: 'random-color-generator',
    name: 'Random Color Generator',
    description: 'Generate random colors for inspiration. Get random HEX, RGB, and color names.',
    shortDescription: 'Generate random colors',
    category: 'color',
    slug: 'random-color-generator',
    icon: 'Shuffle',
    keywords: ['random color', 'color generator', 'random hex', 'random rgb'],
    relatedTools: ['color-palette-generator', 'color-picker'],
  },
  {
    id: 'tailwind-color-converter',
    name: 'Tailwind Color Converter',
    description: 'Convert colors to Tailwind CSS color classes. Find the closest Tailwind color match.',
    shortDescription: 'Convert to Tailwind colors',
    category: 'color',
    slug: 'tailwind-color-converter',
    icon: 'Wind',
    keywords: ['tailwind color', 'tailwind converter', 'tailwind css', 'color converter'],
    relatedTools: ['color-picker', 'hex-to-rgb'],
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert colors between HEX, RGB, HSL, and more. All color formats in one tool.',
    shortDescription: 'Convert between color formats',
    category: 'color',
    slug: 'color-converter',
    icon: 'ArrowLeftRight',
    keywords: ['color converter', 'hex rgb hsl', 'color format', 'color transform'],
    relatedTools: ['hex-to-rgb', 'rgb-to-hex'],
  },

  // ==================== CONVERTER TOOLS ====================
  {
    id: 'csv-to-json',
    name: 'CSV to JSON Converter',
    description: 'Convert CSV data to JSON format. Transform spreadsheet data to JSON objects.',
    shortDescription: 'Convert CSV to JSON',
    category: 'converter',
    slug: 'csv-to-json',
    icon: 'FileSpreadsheet',
    keywords: ['csv to json', 'csv converter', 'spreadsheet to json', 'csv parser'],
    relatedTools: ['json-to-csv', 'json-formatter'],
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV Converter',
    description: 'Convert JSON data to CSV format. Export JSON data for spreadsheets.',
    shortDescription: 'Convert JSON to CSV',
    category: 'converter',
    slug: 'json-to-csv',
    icon: 'FileSpreadsheet',
    keywords: ['json to csv', 'json converter', 'json to spreadsheet', 'export csv'],
    relatedTools: ['csv-to-json', 'json-formatter'],
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML Converter',
    description: 'Convert Markdown to HTML code. Transform Markdown text to ready-to-use HTML.',
    shortDescription: 'Convert Markdown to HTML',
    category: 'converter',
    slug: 'markdown-to-html',
    icon: 'FileCode',
    keywords: ['markdown to html', 'md to html', 'markdown converter', 'md converter'],
    relatedTools: ['html-to-markdown', 'html-formatter'],
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown Converter',
    description: 'Convert HTML code to Markdown format. Transform web content to Markdown.',
    shortDescription: 'Convert HTML to Markdown',
    category: 'converter',
    slug: 'html-to-markdown',
    icon: 'FileCode',
    keywords: ['html to markdown', 'html converter', 'html to md', 'markdown generator'],
    relatedTools: ['markdown-to-html', 'remove-html-tags'],
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text or URLs. Create scannable QR codes for any content.',
    shortDescription: 'Generate QR codes online',
    category: 'converter',
    slug: 'qr-code-generator',
    icon: 'QrCode',
    keywords: ['qr code', 'qr generator', 'qr maker', 'barcode generator'],
    relatedTools: ['barcode-generator', 'url-to-qr-code'],
  },
  {
    id: 'text-to-base64',
    name: 'Text to Base64 Converter',
    description: 'Convert text to Base64 encoding. Encode any text string to Base64 format.',
    shortDescription: 'Convert text to Base64',
    category: 'converter',
    slug: 'text-to-base64',
    icon: 'Binary',
    keywords: ['text to base64', 'base64 encoder', 'encode text', 'base64 converter'],
    relatedTools: ['base64-to-text', 'base64-encode'],
  },
  {
    id: 'base64-to-text',
    name: 'Base64 to Text Converter',
    description: 'Decode Base64 to readable text. Convert Base64 encoded strings back to text.',
    shortDescription: 'Convert Base64 to text',
    category: 'converter',
    slug: 'base64-to-text',
    icon: 'FileText',
    keywords: ['base64 to text', 'base64 decoder', 'decode base64', 'base64 converter'],
    relatedTools: ['text-to-base64', 'base64-decode'],
  },
  {
    id: 'url-to-qr-code',
    name: 'URL to QR Code',
    description: 'Generate QR codes from URLs. Create scannable QR codes for websites.',
    shortDescription: 'Convert URL to QR code',
    category: 'converter',
    slug: 'url-to-qr-code',
    icon: 'Link',
    keywords: ['url to qr', 'url qr code', 'website qr', 'link qr code'],
    relatedTools: ['qr-code-generator', 'url-encode'],
  },
  {
    id: 'unix-time-to-date',
    name: 'Unix Time to Date Converter',
    description: 'Convert Unix timestamp to human-readable date. Transform epoch time to date format.',
    shortDescription: 'Convert Unix time to date',
    category: 'converter',
    slug: 'unix-time-to-date',
    icon: 'Clock',
    keywords: ['unix time', 'epoch converter', 'timestamp to date', 'unix timestamp'],
    relatedTools: ['date-to-unix-time', 'timestamp-converter'],
  },
  {
    id: 'date-to-unix-time',
    name: 'Date to Unix Time Converter',
    description: 'Convert date to Unix timestamp. Transform human-readable date to epoch time.',
    shortDescription: 'Convert date to Unix time',
    category: 'converter',
    slug: 'date-to-unix-time',
    icon: 'Clock',
    keywords: ['date to unix', 'date to timestamp', 'epoch time', 'unix converter'],
    relatedTools: ['unix-time-to-date', 'timestamp-converter'],
  },

  // ==================== MISC TOOLS ====================
  {
    id: 'random-number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers within a range. Get random integers or decimals.',
    shortDescription: 'Generate random numbers',
    category: 'misc',
    slug: 'random-number-generator',
    icon: 'Dice5',
    keywords: ['random number', 'number generator', 'random integer', 'rng'],
    relatedTools: ['dice-roll-simulator', 'coin-flip'],
  },
  {
    id: 'dice-roll-simulator',
    name: 'Dice Roll Simulator',
    description: 'Roll virtual dice online. Simulate dice rolls for games and probability.',
    shortDescription: 'Roll dice online',
    category: 'misc',
    slug: 'dice-roll-simulator',
    icon: 'Dices',
    keywords: ['dice roll', 'dice simulator', 'roll dice', 'virtual dice'],
    relatedTools: ['random-number-generator', 'coin-flip'],
  },
  {
    id: 'coin-flip',
    name: 'Coin Flip Simulator',
    description: 'Flip a virtual coin online. Get random heads or tails results.',
    shortDescription: 'Flip coin online',
    category: 'misc',
    slug: 'coin-flip',
    icon: 'Circle',
    keywords: ['coin flip', 'heads or tails', 'coin toss', 'flip coin'],
    relatedTools: ['dice-roll-simulator', 'random-number-generator'],
  },
  {
    id: 'countdown-timer',
    name: 'Countdown Timer',
    description: 'Create a countdown timer for any event. Set custom duration and track time.',
    shortDescription: 'Create countdown timer',
    category: 'misc',
    slug: 'countdown-timer',
    icon: 'Timer',
    keywords: ['countdown timer', 'timer', 'countdown', 'stopwatch'],
    relatedTools: ['timestamp-converter', 'age-calculator'],
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Generate barcodes from text or numbers. Create various barcode formats.',
    shortDescription: 'Generate barcodes online',
    category: 'misc',
    slug: 'barcode-generator',
    icon: 'Barcode',
    keywords: ['barcode generator', 'barcode maker', 'create barcode', 'barcode creator'],
    relatedTools: ['qr-code-generator', 'url-to-qr-code'],
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between different units of measurement. Length, weight, temperature, and more.',
    shortDescription: 'Convert units online',
    category: 'misc',
    slug: 'unit-converter',
    icon: 'Ruler',
    keywords: ['unit converter', 'convert units', 'measurement converter', 'unit conversion'],
    relatedTools: ['percentage-calculator', 'bmi-calculator'],
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months, days. Find age from date of birth.',
    shortDescription: 'Calculate age from date',
    category: 'misc',
    slug: 'age-calculator',
    icon: 'Calendar',
    keywords: ['age calculator', 'calculate age', 'birthday calculator', 'age finder'],
    relatedTools: ['date-to-unix-time', 'countdown-timer'],
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate your Body Mass Index (BMI). Check if your weight is healthy.',
    shortDescription: 'Calculate BMI online',
    category: 'misc',
    slug: 'bmi-calculator',
    icon: 'Scale',
    keywords: ['bmi calculator', 'body mass index', 'weight calculator', 'health calculator'],
    relatedTools: ['percentage-calculator', 'unit-converter'],
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages easily. Find percentage of a number, increase, decrease.',
    shortDescription: 'Calculate percentages',
    category: 'misc',
    slug: 'percentage-calculator',
    icon: 'Percent',
    keywords: ['percentage calculator', 'calculate percent', 'percent calculator', 'percentage'],
    relatedTools: ['bmi-calculator', 'unit-converter'],
  },
  {
    id: 'password-strength-checker',
    name: 'Password Strength Checker',
    description: 'Check the strength of your password. Get tips to make your passwords more secure.',
    shortDescription: 'Check password strength',
    category: 'misc',
    slug: 'password-strength-checker',
    icon: 'Shield',
    keywords: ['password strength', 'password checker', 'secure password', 'password test'],
    relatedTools: ['random-password-generator', 'base64-encode'],
  },
];

export function getToolById(id: string): Tool | undefined {
  return tools.find(tool => tool.id === id);
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find(tool => tool.slug === slug);
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter(tool => tool.category === category);
}

export function getRelatedTools(toolId: string): Tool[] {
  const tool = getToolById(toolId);
  if (!tool?.relatedTools) return [];

  return tool.relatedTools
    .map(id => getToolById(id))
    .filter((t): t is Tool => t !== undefined);
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase();
  return tools.filter(tool =>
    tool.name.toLowerCase().includes(lowerQuery) ||
    tool.shortDescription.toLowerCase().includes(lowerQuery) ||
    tool.keywords.some(keyword => keyword.toLowerCase().includes(lowerQuery))
  );
}
